### ISSUE TITLE
Backport modification from https://github.com/lronaldo/cpctelera/tree/master/cpctelera/tools/iDSK-0.13 to iDSK

### ISSUE THREAD

**Issue by rgiot** [cpcsdk/cpctools#70]
It seems that some bug fixes to iDSK has been proposed here: https://github.com/lronaldo/cpctelera/tree/master/cpctelera/tools/iDSK-0.13
It is mandatory to review and include them (if not already done)

**Comment by lronaldo** [comment]
My bugfix to iDSK is already pushed to cpctools. I sent and discussed it with pulkomandy 3 months ago :)
https://github.com/cpcsdk/cpctools/commit/a4c7c9524790bed4b201cda6e62facb639ff57d9
